"""
Django settings for Trabalho__Final project.

Generated by 'django-admin startproject' using Django 2.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from dotenv import load_dotenv

# Carrega as variáveis do arquivo .env
load_dotenv()

# Configurações do Django
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')  # Use o nome da variável definida no .env
DEBUG = os.getenv('DJANGO_DEBUG') == 'True'
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS').split(',')  # Use o nome da variável definida no .env

# Configurações de e-mail
EMAIL_HOST = os.getenv('EMAIL_HOST')  # Use o nome da variável definida no .env
EMAIL_PORT = int(os.getenv('EMAIL_PORT'))  # Use o nome da variável definida no .env
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')  # Use o nome da variável definida no .env
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # Use o nome da variável definida no .env
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'  # Use o nome da variável definida no .env
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')  # Use o nome da variável definida no .env

# Configurações do banco de dados
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),  # Use o nome da variável definida no .env
        'USER': os.getenv('DB_USER'),  # Use o nome da variável definida no .env
        'PASSWORD': os.getenv('DB_PASSWORD'),  # Use o nome da variável definida no .env
        'HOST': os.getenv('DB_HOST'),  # Use o nome da variável definida no .env
        'PORT': os.getenv('DB_PORT'),  # Use o nome da variável definida no .env
    }
}



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Media files settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*=hcvkd__d532frp93_cl(6=c2cw2qquj98d0=hptvm+$+qlz1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

STATIC_URL = '/static/'

# AUTHENTICATION
AUTH_USER_MODEL = 'registros.Usuario'
LOGIN_URL = '/registros/login/'
LOGIN_REDIRECT_URL = '/registros/dashboard/'


# Email definitions
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'erika.fernandes1409@gmail.com'
EMAIL_HOST_PASSWORD = 'zjpv elhj mpxo lpoi'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'gerenciador_registros_olímpicos@gmail.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registros',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Trabalho__Final.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Trabalho__Final.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
