# Generated by Django 2.2.9 on 2024-08-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20240802_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='foto_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
