# Generated by Django 2.2.9 on 2024-08-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_auto_20240804_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
