# Generated by Django 2.2.9 on 2024-08-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_usuario_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='token',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
