# Generated by Django 2.2.9 on 2024-08-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_auto_20240805_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
