# Generated by Django 2.2.9 on 2024-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0015_auto_20240805_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
