# Generated by Django 2.2.9 on 2024-07-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20240714_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.CharField(default='', max_length=500),
        ),
    ]
