# Generated by Django 2.2.9 on 2024-07-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20240714_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cor_preferida',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
