# Generated by Django 2.2.9 on 2024-07-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_usuario_cor_preferida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cor_preferida',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
    ]
